### ISSUE TITLE
The DateRange Mechanism for Portal

### ISSUE THREAD

**Issue by pmbohm** [aodn-archive/DELETE_ME.geoserver-layer-filter-extension#9]
### What is needed

The '_map' layers, those layers for visualisation that have attributes, start_time and end_time are intended to be displayed in a single dateRange filter in the portal. The user picks a date range and when downloading the corresponding '_data' layer has a single attribute eg: time. The resulting download contains all matching Time's within the DateRange

**Comment by dnahodil** [comment]
Currently this must be configured manually by editing the XML. When we're happy the behaviour is correct we should update the filter UI so it can be done through the front end.
